#!/usr/bin/env python3
"""
Pi NHL Scoreboard — JMCScoreboard
==================================
Hardware: Raspberry Pi + Adafruit RGB Matrix Bonnet/HAT
Display:  64x32 LED Matrix (P5 - 5mm pitch)

Generated by Pi Scoreboard Builder
See Configure page to adjust broadcast delay, brightness, and team settings.
"""

import time
import sys
import collections
import json
import urllib.request

try:
    from rgbmatrix import RGBMatrix, RGBMatrixOptions, graphics
except ImportError:
    print("Error: rgbmatrix library not found.")
    print("Run: sudo bash setup.sh")
    sys.exit(1)

# ── Settings ──────────────────────────────────────────────────────────────────
BROADCAST_DELAY_SECONDS = 0   # Set to match your TV delay (0=live, 30=cable, 60=streaming)
GPIO_SLOWDOWN           = 2   # Try 3 or 4 if display flickers
BRIGHTNESS              = 80  # 0–100
POLL_INTERVAL_SECONDS   = 30  # How often to check NHL scores

# ── Delay Buffer ──────────────────────────────────────────────────────────────
class DelayBuffer:
    def __init__(self, delay_seconds):
        self.delay = delay_seconds
        self._queue = collections.deque()

    def push(self, data):
        self._queue.append((time.monotonic(), data))

    def pop_ready(self):
        now = time.monotonic()
        ready = None
        while self._queue and (now - self._queue[0][0]) >= self.delay:
            _, ready = self._queue.popleft()
        return ready


# ── Matrix ────────────────────────────────────────────────────────────────────
def create_matrix():
    options = RGBMatrixOptions()
    options.rows = 32
    options.cols = 64
    options.chain_length = 1
    options.parallel = 1
    options.hardware_mapping = 'adafruit-hat'
    options.gpio_slowdown = GPIO_SLOWDOWN
    options.brightness = BRIGHTNESS
    options.disable_hardware_pulsing = True
    options.drop_privileges = False
    return RGBMatrix(options=options)


def load_font(path, fallback=None):
    f = graphics.Font()
    try:
        f.LoadFont(path)
    except Exception:
        if fallback:
            try: f.LoadFont(fallback)
            except Exception: pass
    return f


def draw_game(matrix, data):
    canvas = matrix.CreateFrameCanvas()
    font  = load_font("/home/pi/rpi-rgb-led-matrix/fonts/5x7.bdf")
    small = load_font("/home/pi/rpi-rgb-led-matrix/fonts/4x6.bdf",
                      "/home/pi/rpi-rgb-led-matrix/fonts/5x7.bdf")
    large = load_font("/home/pi/rpi-rgb-led-matrix/fonts/9x18B.bdf",
                      "/home/pi/rpi-rgb-led-matrix/fonts/5x7.bdf")

    c1    = graphics.Color(*data.get("color1", [255, 68, 68]))
    c2    = graphics.Color(*data.get("color2", [68, 136, 255]))
    white = graphics.Color(255, 255, 255)
    dim   = graphics.Color(60, 60, 60)

    graphics.DrawText(canvas, font, 1,  8, c1, data.get("team1", "HOM")[:3])
    graphics.DrawText(canvas, font, 45, 8, c2, data.get("team2", "AWY")[:3])
    graphics.DrawLine(canvas, 0, 10, 63, 10, dim)
    graphics.DrawText(canvas, large, 6,  28, c1, str(data.get("score1", 0)))
    graphics.DrawText(canvas, large, 40, 28, c2, str(data.get("score2", 0)))
    graphics.DrawLine(canvas, 29, 20, 34, 20, white)

    state = data.get("state", "")
    if state == "LIVE":
        status = "P{} {}".format(data.get("period", ""), data.get("clock", "")).strip()
        graphics.DrawText(canvas, small, 1, 32, dim, status[:14])
    elif state == "FINAL":
        graphics.DrawText(canvas, small, 18, 32, dim, "FINAL")

    matrix.SwapOnVSync(canvas)


def draw_idle(matrix):
    canvas = matrix.CreateFrameCanvas()
    font  = load_font("/home/pi/rpi-rgb-led-matrix/fonts/5x7.bdf")
    small = load_font("/home/pi/rpi-rgb-led-matrix/fonts/4x6.bdf",
                      "/home/pi/rpi-rgb-led-matrix/fonts/5x7.bdf")
    gold  = graphics.Color(255, 184, 28)
    blue  = graphics.Color(51, 102, 255)
    graphics.DrawText(canvas, font,  18, 12, gold, "NHL")
    graphics.DrawText(canvas, small,  6, 24, blue, "SCOREBOARD")
    matrix.SwapOnVSync(canvas)


# ── NHL Score Fetcher ─────────────────────────────────────────────────────────
TEAM_COLORS = {
    "ANA":[244,122,56],"ARI":[140,38,51],"BOS":[255,184,28],"BUF":[0,48,135],
    "CGY":[200,16,46],"CAR":[204,0,0],"CHI":[207,10,44],"COL":[111,38,61],
    "CBJ":[0,38,84],"DAL":[0,104,71],"DET":[206,17,38],"EDM":[255,76,0],
    "FLA":[4,30,66],"LAK":[17,17,17],"MIN":[21,71,52],"MTL":[175,30,45],
    "NSH":[255,184,28],"NJD":[206,17,38],"NYI":[0,48,135],"NYR":[0,56,168],
    "OTT":[197,32,50],"PHI":[247,73,2],"PIT":[252,181,20],"STL":[0,47,135],
    "SJS":[0,109,117],"SEA":[0,22,40],"TBL":[0,40,104],"TOR":[0,62,126],
    "VAN":[0,132,61],"VGK":[180,151,90],"WSH":[200,16,46],"WPG":[4,30,66],
}

def fetch_scores():
    url = "https://api-web.nhle.com/v1/scoreboard/now"
    try:
        with urllib.request.urlopen(url, timeout=10) as r:
            data = json.loads(r.read().decode())
        games = data.get("gamesByDate", [{}])[0].get("games", [])
        results = []
        for g in games:
            away = g.get("awayTeam", {})
            home = g.get("homeTeam", {})
            state = g.get("gameState", "")
            live  = state in ("LIVE", "CRIT")
            final = state in ("FINAL", "OFF")
            results.append({
                "id":     g.get("id"),
                "team1":  away.get("abbrev", "???"),
                "team2":  home.get("abbrev", "???"),
                "score1": away.get("score", 0),
                "score2": home.get("score", 0),
                "color1": TEAM_COLORS.get(away.get("abbrev",""), [255,68,68]),
                "color2": TEAM_COLORS.get(home.get("abbrev",""), [68,136,255]),
                "period": str(g.get("period", "")),
                "clock":  g.get("clock", {}).get("timeRemaining", ""),
                "state":  "LIVE" if live else ("FINAL" if final else "UPCOMING"),
            })
        return results
    except Exception as e:
        print("Score fetch error:", e)
        return []


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    print("=" * 50)
    print("  JMC Pi NHL Scoreboard")
    print("  Delay : {}s  |  Brightness : {}%".format(BROADCAST_DELAY_SECONDS, BRIGHTNESS))
    print("  Press CTRL+C to stop")
    print("=" * 50)

    matrix = create_matrix()
    buf    = DelayBuffer(BROADCAST_DELAY_SECONDS)
    last_fetch = 0

    try:
        while True:
            now = time.monotonic()

            # Fetch scores periodically
            if now - last_fetch >= POLL_INTERVAL_SECONDS:
                games = fetch_scores()
                last_fetch = now
                if games:
                    # Pick the first live game, else first game of the day
                    live_games = [g for g in games if g["state"] == "LIVE"]
                    game = live_games[0] if live_games else games[0]
                    buf.push(game)
                    print("Fetched: {} {} – {} {}  [{}]".format(
                        game["team1"], game["score1"],
                        game["team2"], game["score2"],
                        game["state"]
                    ))

            ready = buf.pop_ready()
            if ready is not None:
                draw_game(matrix, ready)
            else:
                draw_idle(matrix)

            time.sleep(1)

    except KeyboardInterrupt:
        print("\nShutting down...")
        matrix.Clear()
        sys.exit(0)


if __name__ == "__main__":
    main()
